#!/bin/sh
# gtkdialog4 example: pulse (progressbar pulsé)
GTKDIALOG=${GTKDIALOG:-gtk4sermo}

MAIN_DIALOG='
<window title="Progression indéterminée" border-width="12">
  <vbox spacing="10">
    <text><label>Traitement en cours…</label></text>
    <pulse active="true">
      <variable>PB_MAIN</variable>
      <label>Chargement</label>
          </pulse>
    <hseparator></hseparator>
    <hbox homogeneous="true">
      <button cancel></button>
    </hbox>
  </vbox>
</window>
'
export MAIN_DIALOG
case $1 in
  -d | --dump) echo "$MAIN_DIALOG" ;;
  *) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
