#!/bin/sh
# gtkdialog4 example: password widget
GTKDIALOG=${GTKDIALOG:-gtk4sermo}

MAIN_DIALOG='
<window title="Authentification" border-width="12">
  <vbox spacing="10">
    <hbox>
      <text><label>Utilisateur :</label></text>
      <entry><variable>ENT_USER</variable></entry>
    </hbox>
    <hbox>
      <text><label>Mot de passe :</label></text>
      <password placeholder-text="Mot de passe…">
        <variable>ENT_PASS</variable>
              </password>
    </hbox>
    <hseparator></hseparator>
    <hbox homogeneous="true">
      <button ok></button>
      <button cancel></button>
    </hbox>
  </vbox>
</window>
'
export MAIN_DIALOG
case $1 in
  -d | --dump) echo "$MAIN_DIALOG" ;;
  *) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
