#!/bin/bash
# garde_fonctions_interdites.sh — SECURITY.md et les deux TODO-SECURITY.md
# affirment qu'aucune fonction interdite n'est APPELÉE dans src/ :
# strcpy, strcat, sprintf, vsprintf, gets, system, popen, atof, strtod.
#
# atof et strtod sont là pour une raison précise : ils lisent la virgule de la
# LOCALE. Sous fr_FR.UTF-8, strtod("0.9") rend 0,000 — en silence, sans erreur.
# C'est ce qui rendait les deux ports inutilisables en français avant le
# 2026-08-22. g_strtod et g_ascii_strtod ne matchent pas : le caractère qui les
# précède est un souligné, exclu de la frontière de mot à gauche.
#
# Une affirmation pareille vieillit mal : elle est vraie le jour où on l'écrit,
# et personne ne la revérifie. Ce banc la rend tenable.
#
# Deux pièges, et c'est tout l'intérêt du banc :
#
#  1. Les COMMENTAIRES citent ces noms légitimement — safe_exec.c explique
#     justement qu'il remplace system() et popen(). Les compter serait un faux
#     positif permanent, et un banc qui crie tout le temps finit ignoré. On
#     retire donc les commentaires avant de chercher.
#  2. Des noms plus longs CONTIENNENT ces noms : safe_system, g_strdup_printf,
#     g_snprintf. Il faut une frontière de mot À GAUCHE aussi, sinon
#     safe_system compte pour system.
#
# Usage : garde_fonctions_interdites.sh <dossier-src>

set -u
SRC="${1:-}"
[ -d "$SRC" ] || { echo "usage: $0 <dossier-src>" >&2; exit 2; }

INTERDITES='strcpy|strcat|sprintf|vsprintf|gets|system|popen|atof|strtod'

# Les fichiers engendrés par flex/bison sont hors de notre plume : on ne les juge pas.
est_engendre() {
	head -n 40 "$1" | LC_ALL=C grep -qaE 'A Bison parser, made by|Generated by (GNU )?[Ff]lex|generated by flex'
}

trouves=0
ignores=0
examines=0

for f in "$SRC"/*.c "$SRC"/*.h; do
	[ -e "$f" ] || continue
	if est_engendre "$f"; then ignores=$((ignores + 1)); continue; fi
	examines=$((examines + 1))

	# Retirer commentaires /* */ et // avant de chercher, en gardant les numéros
	# de ligne : sed seul ne sait pas suivre un /* */ multiligne, awk si.
	# LC_ALL=C : une partie des fichiers hérités est en ISO-8859-1. Sous une locale
	# UTF-8, awk crie « données multioctets incorrectes » sur chacun — du bruit qui
	# noierait un vrai signalement. En C, un octet est un octet.
	hits=$(LC_ALL=C awk '
		{ ligne = $0 }
		{
			out = ""
			i = 1
			while (i <= length(ligne)) {
				c  = substr(ligne, i, 1)
				c2 = substr(ligne, i, 2)
				if (dans_bloc) {
					if (c2 == "*/") { dans_bloc = 0; i += 2 } else { i++ }
					continue
				}
				if (c2 == "/*") { dans_bloc = 1; i += 2; continue }
				if (c2 == "//") { break }
				out = out c
				i++
			}
			print FILENAME ":" FNR ":" out
		}
	' "$f" | LC_ALL=C grep -naE "(^|[^A-Za-z0-9_])(${INTERDITES})[[:space:]]*\(" || true)

	if [ -n "$hits" ]; then
		echo "$hits" | sed 's/^[0-9]*://' | while IFS= read -r l; do
			echo "  ✘ $l"
		done
		n=$(printf '%s\n' "$hits" | grep -c .)
		trouves=$((trouves + n))
	fi
done

if [ "$examines" -eq 0 ]; then
	echo "ÉCHEC — aucun fichier examiné dans $SRC : le banc ne prouve rien." >&2
	exit 1
fi

echo "garde_fonctions_interdites : $examines fichier(s) examiné(s), $ignores engendré(s) ignoré(s)."

if [ "$trouves" -gt 0 ]; then
	cat >&2 <<'MSG'

ÉCHEC — appel(s) à une fonction interdite dans src/.

SECURITY.md et TODO-SECURITY.md affirment qu'il n'y en a aucun. Soit on corrige
l'appel, soit on corrige l'affirmation — mais les deux ne peuvent pas coexister.

Remplacements d'usage :
  strcpy/strncpy → g_strlcpy      sprintf  → g_snprintf ou g_strdup_printf
  strcat/strncat → g_strlcat      system   → safe_system
  gets           → jamais         popen    → safe_popen
  atof/strtod    → g_ascii_strtod (la locale ne doit pas décider du sens
                   d'un nombre écrit dans un fichier XML)
MSG
	exit 1
fi

echo "garde_fonctions_interdites : OK — aucun appel interdit."
exit 0
