#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# tests/garde_spdx.sh — tout fichier source C, C++, Flex ou Bison porte un SPDX.
#
# LICENCES.md affirme que les fichiers C et C++ portent un identifiant SPDX.
# L'affirmation a été fausse deux fois : 5 fichiers sur 115 au début, puis le
# lexer, le parser, les .cpp et les en-têtes de _shim/ — que ce banc ne regardait
# pas : il ne lisait que les *.c et *.h du SEUL dossier donné. Il descend
# désormais dans les sous-dossiers et lit .c .h .cc .cpp .hpp .l .y.
#
# ⚠ grep -a est obligatoire : plusieurs fichiers hérités de l'amont ont été en
# ISO-8859-1, et grep sans -a les prend pour du binaire, donc les SAUTE en silence.
#
# Exclus : les fichiers PRODUITS par flex et bison (ils n'existent que dans un
# arbre compilé) et le code tiers embarqué (dossier imgui/, Dear ImGui, sous sa
# propre licence MIT déclarée dans LICENCES.md).
#
# Usage : garde_spdx.sh <dossier>
SRCDIR="${1:?usage: garde_spdx.sh /chemin/vers/dossier}"
[[ -d "$SRCDIR" ]] || { echo "repertoire introuvable : $SRCDIR" >&2; exit 2; }

genere() {
    head -c 4096 "$1" | grep -aqE 'A lexical scanner generated by flex|A Bison parser, made by|Bison implementation for Yacc'
}

# Dans un dépôt git, on lit les fichiers SUIVIS — ce qui est publié —, pas le
# disque : un arbre compilé contient des fichiers produits (moc de Qt, en-têtes
# installés) qui feraient échouer le banc chez qui a construit, et passer chez
# qui ne l'a pas fait. Hors dépôt (le témoin), on parcourt le disque.
lister() {
    if git -C "$1" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        (cd "$1" && git ls-files -z -- '*.c' '*.h' '*.cc' '*.cpp' '*.hpp' '*.l' '*.y' ':!:*imgui/*')
    else
        (cd "$1" && find . -type d -name imgui -prune -o -type f \( -name '*.c' -o -name '*.h' -o -name '*.cc' \
            -o -name '*.cpp' -o -name '*.hpp' -o -name '*.l' -o -name '*.y' \) -printf '%P\0')
    fi
}

compter() {  # compter <dossier> → remplit manquants[], total, ignores
    manquants=(); total=0; ignores=0
    while IFS= read -r -d '' f; do
        if genere "$1/$f"; then ignores=$((ignores+1)); continue; fi
        total=$((total+1))
        head -c 4096 "$1/$f" | grep -aq 'SPDX-License-Identifier' || manquants+=("$f")
    done < <(lister "$1")
}

# Témoin : un fichier sans identifiant, rangé dans un SOUS-dossier, doit être vu.
T=$(mktemp -d); trap 'rm -rf "$T"' EXIT
mkdir -p "$T/sous"; printf '/* SPDX-License-Identifier: MIT */\nint a;\n' > "$T/ok.c"; printf 'int b;\n' > "$T/sous/nu.l"
compter "$T"
if (( ${#manquants[@]} != 1 )); then
    echo "ECHEC DU TEMOIN : un fichier sans SPDX dans un sous-dossier n'est pas vu"; exit 1
fi

compter "$SRCDIR"
(( total > 0 )) || { echo "ECHEC : aucun fichier source trouve dans $SRCDIR"; exit 1; }

if (( ${#manquants[@]} > 0 )); then
    echo "ECHEC : ${#manquants[@]} fichier(s) sur $total sans SPDX-License-Identifier :"
    printf '    %s\n' "${manquants[@]}"
    exit 1
fi
echo "OK : $total fichiers source, tous avec un identifiant SPDX (${ignores} fichier(s) genere(s) ignore(s))"
