#!/bin/sh
# postinst — gtk3dialog
set -e
case "$1" in
    configure)
        # Compat symlink: gtkdialog → gtk3dialog (rétrocompatibilité)
        if [ ! -e /usr/bin/gtkdialog ]; then
            ln -s /usr/bin/gtk3dialog /usr/bin/gtkdialog
        fi
        ;;
esac
#DEBHELPER#
exit 0
