#!/bin/sh
# gtkdialog4 example: stack widget (GTK4-natif)
GTKDIALOG=${GTKDIALOG:-gtk4sermo}

MAIN_DIALOG='
<window title="Stack multi-pages" border-width="12">
  <vbox spacing="10">
    <hbox homogeneous="true">
      <button>
        <label>Page 1</label>
        <action>refresh:STK_MAIN</action>
        <variable>BTN_P1</variable>
      </button>
      <button>
        <label>Page 2</label>
        <action>refresh:STK_MAIN</action>
      </button>
      <button>
        <label>Page 3</label>
        <action>refresh:STK_MAIN</action>
      </button>
    </hbox>
    <hseparator></hseparator>
    <stack transition="slide-left-right">
      <vbox name="page0">
        <text><label>Contenu de la Page 1</label></text>
        <entry><variable>ENT_P1</variable><default>Donnée page 1</default></entry>
      </vbox>
      <vbox name="page1">
        <text><label>Contenu de la Page 2</label></text>
        <checkbox><label>Option A</label><variable>CHK_P2</variable></checkbox>
      </vbox>
      <vbox name="page2">
        <text><label>Contenu de la Page 3</label></text>
        <spinbutton range-min="0" range-max="100"><variable>SB_P3</variable></spinbutton>
      </vbox>
      <variable>STK_MAIN</variable>
    </stack>
    <hseparator></hseparator>
    <hbox homogeneous="true">
      <button ok></button>
    </hbox>
  </vbox>
</window>
'
export MAIN_DIALOG
case $1 in
  -d | --dump) echo "$MAIN_DIALOG" ;;
  *) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
