#!/bin/sh
# gtkdialog4 example: switch widget
GTKDIALOG=gtkdialog4

MAIN_DIALOG='
<window title="Switch" border-width="12">
  <vbox spacing="10">
    <text><label>Activer le mode nuit :</label></text>
    <switch>
      <variable>SW_NUIT</variable>
      <default>false</default>
      <action>echo "Mode nuit : $SW_NUIT"</action>
    </switch>
    <hseparator></hseparator>
    <hbox homogeneous="true">
      <button ok></button>
    </hbox>
  </vbox>
</window>
'
export MAIN_DIALOG
case $1 in
  -d | --dump) echo "$MAIN_DIALOG" ;;
  *) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
