#!/bin/sh
# gtkdialog4 example: infobar widget
GTKDIALOG=${GTKDIALOG:-gtk4sermo}

MAIN_DIALOG='
<window title="Barre d'\''info" border-width="12">
  <vbox spacing="10">
    <infobar message-type="info">
      <variable>IB_MAIN</variable>
      <label>Ceci est un message d'\''information GTK4.</label>
    </infobar>
    <infobar message-type="warning">
      <label>Attention : action irréversible.</label>
    </infobar>
    <hbox homogeneous="true">
      <button ok></button>
    </hbox>
  </vbox>
</window>
'
export MAIN_DIALOG
case $1 in
  -d | --dump) echo "$MAIN_DIALOG" ;;
  *) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
