#!/bin/sh
# gtkdialog4 example: filechooser widget
GTKDIALOG=${GTKDIALOG:-gtk4sermo}

MAIN_DIALOG='
<window title="Sélecteur de fichier" border-width="12">
  <vbox spacing="10">
    <filechooser>
      <variable>FILE_SELECTED</variable>
      <action>refresh:ENT_FILE</action>
    </filechooser>
    <hseparator></hseparator>
    <hbox>
      <text><label>Fichier :</label></text>
      <entry>
        <variable>ENT_FILE</variable>
        <input>echo "$FILE_SELECTED"</input>
      </entry>
    </hbox>
    <hbox homogeneous="true">
      <button ok></button>
      <button cancel></button>
    </hbox>
  </vbox>
</window>
'
export MAIN_DIALOG
case $1 in
  -d | --dump) echo "$MAIN_DIALOG" ;;
  *) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
